### ISSUE TITLE
feed plugin: PHP Warning:  date() expects parameter 2 to be long

### ISSUE THREAD

**Issue by francoisromain** [getkirby/plugins#31] opened 2015-08-25 16:47 UTC
the feed plugin makes an error in the php logs

    PHP Warning:  date() expects parameter 2 to be long, string given in /srv/data/web/vhosts/mysite.com/htdocs/site/plugins/feed/template.php on line 8

**Comment by lukasbestle** [comment] 2015-08-25 17:05
This is a duplicate of #21.

**Comment by francoisromain** [comment] 2015-08-25 17:11
@lukasbestle sorry about that

**Comment by jolantis** [comment] 2015-08-25 17:16
See issue #21.

**Comment by lukasbestle** [comment] 2015-08-25 17:45
No problem at all, but to keep everything clean, please close this issue.
BTW: You can find the fix for this in #21 until it is officially fixed by the core team.

**Closed** 2015-08-25 18:23 UTC
